- name: Reload Systemd
  ansible.builtin.systemd:
    scope: user
    daemon_reload: yes
  become: yes
  become_user: "{{ deployer_user_name }}"

- name: Restart Backend
  ansible.builtin.systemd:
    scope: user
    name: textreview-backend
    state: restarted
  become: yes
  become_user: "{{ deployer_user_name }}"